services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paw_salon
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 10s
      retries: 5
      timeout: 10s

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
        restart: true
